### ISSUE TITLE
Consider adding a getExtraOptions() method

### ISSUE THREAD

**Issue by moufmouf** [container-interop/definition-interop#10]
We are only standardizing the most common options out there (entry building via the new keyword and via a factory).
But there are really a huge number of different options in containers out there.
For instance: lazy loading via proxying, inlining of instances, etc...

Of course we cannot build an interface that would contain all possible features (in particular because some of those feature might not yet exist).

So I was wondering if we should not consider an extra options array (a bit like in Composer's extra section), where one could store container specific settings.

For instance:

``` php
$options = $definition->getExtraOptions();
if (isset($options['lazy']) && $options['lazy']) {
   // Add proxying if the container supports it.
}
```

I'm not completely sure of the idea though, I'm just opening the question it to gather some feedback.

**Comment by mnapoli** [comment]
We are writing interfaces instead of reference implementations to allow implementations to have any additional method they want. So I don't see the point of having an array of options when definitions can have any extra method/properties.

**Comment by moufmouf** [comment]
Mmmmm... yeah. My point was that some of these features are available across containers (for instance "lazy" loading), so I don't want to have to use a "Symfony" implementation of _definition-interop_ interfaces to be able to use this feature.

But you are right, this smells fishy... I'm closing the issue until we find a better way.

**Comment by mnapoli** [comment]
In that case someone could come up with an interface like that:

``` php
interface LazyDefinitionInterface
{
    public function isLazy();
}
```

and containers could become compatible with it (it could even become standard at some point).
