### ISSUE TITLE
Pushing packages on Packagist

### ISSUE THREAD

**Issue by moufmouf** [container-interop/definition-interop#11]
We start investing a lot of time in this project and it seems unlikely we are going to stop anywhere before world domination... hum... I mean _full package interoperability_.

It starts to be cumbersome to add the "repositories" section in all my composer.json files... for definition-interop, for yaco, for assembly, for yaml-definitions-loader....

What if we pushed all those packages to Packagist?

**Comment by mnapoli** [comment]
:+1: would be useful for me too ;)

**Comment by mnapoli** [comment]
Also I'll be pushing a update to #8, after that is merged we could tag a 0.1.0? It would be much more practical (BC breaks allowed between 0.x versions of course).

**Comment by moufmouf** [comment]
Completely agree. It's exhausting to have to change immediately every package on each minor change.

**Comment by moufmouf** [comment]
Done. Just created packagist package for definition-interop.
