### ISSUE TITLE
Tag 0.1.0

### ISSUE THREAD

**Issue by mnapoli** [container-interop/definition-interop#12]
OK to tag 0.1.0? That will make creating/updating packages easier with tagged versions, and there are no BC breaking issues open for now.

**Comment by Guillaume-Rossignol** [comment]
:+1:

**Comment by prisis** [comment]
:+1:

**Comment by mnapoli** [comment]
We'll need to fix the Packagist configuration first, it's not set up as auto-updating so it won't pick up anything new anyway.

**Comment by moufmouf** [comment]
:+1: ...and done!
