### ISSUE TITLE
Provide a standard test suite to test containers / compilers

### ISSUE THREAD

**Issue by moufmouf** [container-interop/definition-interop#19]
We see that there are a lot of cases to be discussed, and the implementation of _definition-interop_ could be tricky for some containers / compilers.
I'm proposing here to write an abstract unit test that provides definition providers to the tested container and that tests the results from the container.

I've already written the package here: https://github.com/moufmouf/definition-interop-compiler-test-suite

If you agree, I'll move it to the container-interop project.
There are many things to be discussed in these tests, so they are definitely not final, but if we manage to share a common set of unit tests, we will be sure to have more compatible container implementations.

Here is a typical implementation of the unit test in Yaco: https://github.com/thecodingmachine/yaco/blob/1.0/tests/DefinitionInteropCompatibilityTest.php

**Comment by mnapoli** [comment]
That's great stuff! I'm +1 to move it here.

**Comment by moufmouf** [comment]
Done!

Migrated here: https://github.com/container-interop/definition-interop-compiler-test-suite

**Comment by Anahkiasen** [comment]
Out of curiosity why not put the tests in the `definition-interop` repo directly? Don't you need one to use the other and vice versa?

**Comment by moufmouf** [comment]
One of the reasons: the tests need mnapoli/assembly and phpunit/phpunit to run, which we don't want to add in the "require" section of definition-interop's composer.json.

Also, adding this to the "require-dev" section is not possible because the "require-dev" dependencies of dependencies are not fetched (only the "require-dev" dependencies of the root package are fetched in composer).

**Comment by Anahkiasen** [comment]
Ah yes makes sense
